---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Extracts a value from a TOX configuration file (tox.ini)
name: "📦 Extract TOX Configuration Value"

inputs:
  # Mandatory
  TOX_KEY:
    description: "Key to search in tox.ini file"
    type: string
    required: true
  # Optional
  TOX_CONFIG_PATH:
    description: "Path to tox.ini configuration file"
    type: string
    required: false
    default: "tox.ini"
  TOX_ENVIRONMENT:
    description: "TOX environment to query"
    type: string
    required: false
  AWK_ARGS:
    description: "AWK arguments to manipulate returned value"
    type: string
    required: false
  SED_ARGS:
    description: "SED arguments to manipulate returned value"
    type: string
    required: false

outputs:
  TOX_VALUE:
    description: "Value extracted using input/query parameters"
    value: ${{ steps.parse-tox.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: "Parse TOX configuration file: ${{ inputs.TOX_FILE_PATH }}"
      id: parse-tox
      shell: bash
      run: |
        # 🔍 Parse TOX configuration file

        PYTHON_CMD=$(which python)
        if [ ! -x $PYTHON_CMD ]; then
          echo "Unable to run Python command ❌"
          echo "Call setup-python before calling"
          exit 1
        fi

        TOX_CMD=$(which tox)
        if [ ! -x $TOX_CMD ]; then
          "$PYTHON_CMD" -m venv /tmp/tox
          if ! (pip install --upgrade --disable-pip-version-check -q tox > /dev/null); then
            echo "Unable to use pip to install tox command ❌"; exit 1
          else
            echo "Successfully installed tox in virtual environment ✅"
          fi
          TOX_CMD=$(which tox)
        fi

        # Process optional inputs
        if [ -n ${{ inputs.TOX_ENVIRONMENT }} ]; then
          TOX_ENV_STRING="-e${{ inputs.TOX_ENVIRONMENT }}"
        fi
        set -o noglob
        AWK_ARGS="${{ inputs.AWK_ARGS }}"
        SED_ARGS="sed ${{ inputs.SED_ARGS }}"
        set +o noglob

        # Build shell command
        # e.g. tox config -c docs/tox.ini -edocs | grep base_python | awk '{print $3}' | sed "s:python::g"
        TOX_COMMAND="$TOX_CMD config -c ${{ inputs.TOX_CONFIG_PATH }} $TOX_ENV_STRING"
        echo "TOX command: $TOX_COMMAND"
        TOX_OUTPUT=$($TOX_COMMAND)

        if [ -n "$AWK_ARGS" ]; then
          RETURN_VALUE=$(echo "$TOX_OUTPUT" | awk $AWK_ARGS)
        fi
        if [ -n "$SED_ARGS" ]; then
          RETURN_VALUE=$(echo "$RETURN_VALUE" | sed $SED_ARGS)
        fi

        # Report/return results
        if [ -z "$RETURN_VALUE" ]; then
          echo "Query failed; empty return value ❌"
        else
          echo "Returning value: $RETURN_VALUE ✅"
        fi
        echo "tox_value=$RETURN_VALUE" >> "$GITHUB_ENV"
        echo "tox_value=$RETURN_VALUE" >> "$GITHUB_OUTPUT"
